import { Inter, Montserrat, Noto_Sans, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/navbar/navbar";
import Footer from "@/components/layouts/footer/footer";
import Providers from "@/components/providers/providers";

// const inter = Noto_Sans({ subsets: ["latin"], weight:["100", "300", "400", "500", "700", "900"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="w-full min-h-screen flex flex-col">
            <Navbar />
            <div className="flex-1">
              {children}
            </div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
